---
title: "p8105_hw6_sc5078"
author: "Yvonne Chen"
output: github_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
set.seed(1)

```

# Problem 2
## Import dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
## Fit with linear regression model
```{r}
fit = lm(tmax ~ tmin + prcp, data = weather_df)

fit |> 
  broom::glance()

fit |> 
  broom::tidy()
```

## Bootstrap
### Estimate log($\hat{\beta_1}$ * $\hat{\beta_2}$)
```{r}
log_result = 
  weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df) ),
    results = map(models, broom::tidy)) |> 
  select(-strap, -models) |> 
  unnest(results) |> 
  mutate(
    beta_1 = ifelse(term == "tmin", estimate, NA),
    beta_2 = ifelse(term == "prcp", estimate, NA))|>
  select(beta_1, beta_2) |>
  mutate_all(~c(.[!is.na(.)], .[is.na(.)])) |>
  na.omit() |>
  mutate(log_beta = log(beta_1 * beta_2))

##  95% CI
log_result |>
  summarize(
    ci_lower = quantile(log_beta, 0.025, na.rm = TRUE), 
    ci_upper = quantile(log_beta, 0.975, na.rm = TRUE))

## Distribution of the estimator
log_result |>
  ggplot(aes(x = log_beta)) + geom_density()

```


### Estimate \( r^2 \)
```{r}
result_r_square = 
  weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df) ),
    results = map(models, broom::glance)) |> 
  select(-strap, -models) |> 
  unnest(results)

## 95% CI
result_r_square |>
  summarize(
    ci_lower = quantile(r.squared, 0.025), 
    ci_upper = quantile(r.squared, 0.975))

## Distribution of the estimator
result_r_square |>
  ggplot(aes(x = r.squared)) + geom_density()
```


